all:
	cd beacon-check && qmake && make && cd ..
	cd beacon-send && qmake && make && cd ..

clean:
	cd beacon-check && make clean && cd ..
	cd beacon-send && make clean && cd ..

distclean:
	cd beacon-check && make distclean && cd ..
	cd beacon-send && make distclean && cd ..	
